import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import GenresPage from "./genres/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type PropType = { children: React.ReactNode};

export default function RootLayout({children}: Readonly<PropType>) {

  return (
    <html lang="en">
      <body className="body">
      <div className="header"> <Header/> </div>
      <div className="genreBar"> <GenresPage/> </div>
      <div className="childrenPage"> {children} </div>
      </body>
    </html>
  );
}
